---
# Source: mq-quarkus-app/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-quarkus-app
data:
  CHANNEL: IBM.APP.SVRCONN
  CONNECTION_NAME: qm1-ibm-mq.dev.svc.cluster.local(1414)
  QM: QM1
  QUEUE_NAME: IBM.DEMO.Q
  APP_NAME: MQ-QUARKUS-APP
  PORT: "1414"
  HOST: qm1-ibm-mq.dev.svc.cluster.local